### ISSUE TITLE
Usage without "depot_verifier.ini" and AcfDir

### ISSUE THREAD

**Issue by KopiNinja** [denvicar/depot_verifier#1]
Hello denvicar!
I was wondering if there is any way to use without a "depot_verifier.ini" file and without the "AcfDir".
What i was looking for is a way to just pass the game manifest and directory as a parameter and see if everything is fine, like "depot_verifier.exe manifest.manifest gameDir/".

**Comment by denvicar** [comment]
Hi, I updated the application and now it's possible to do it (also added a binary release).
You just need to specify a -g flag for the game and a -m flag for the manifest, the readme was updated too.

**Comment by KopiNinja** [comment]
Thank you, everything is working great!
